name: Deploy on killerKoda
on:
  push:
    branches:
     - main
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: set up kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s 
        https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin
    - name: setup kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" >
        $HOME/.kube/config
    - name: deploy to kubernetes
      run: kubectl apply -f 
    
